### ISSUE TITLE
Question : TypeError : expectTypeOf is not a function

### ISSUE THREAD

**Issue by rutonyru** [japa/expect-type#1]
### Package version

2.0.1

### Describe the bug

Hi, 
It's probably a bad configuration of the package... but I don't know where to find some help. 
I simply tried to install the package as follows in the doc : https://japa.dev/docs/plugins/expect-type#installation 
1. Install with npm (npm i -D @japa/expect-type) : ok 
2. Add the configuration to the bin/test.ts file : ok
3. Write 2 tests as documented
   test('Read The test user', async ({ expectTypeOf }) => {
   expectTypeOf({ foo : 'bar' }).toEqualTypeOf<{ foo : string }>() 
4. or : 
   test('Read The test user', async ({ expectTypeOf }) => {
   const usertest = await User.findByOrFail('email', 'test1@example.com') 
   expectTypeOf<typeof usertest>().toMatchTypeOf<User>() })
   

I got the same error when running test (node ace test)
TypeError : expectTypeOf is not a function.

Have I missed something?
Thanks,
Antoine

**Comment by Julien-R44** [comment]
do you have a `"module": "NodeNext",` or `"moduleResolution": "NodeNext"` ( or at least Node16 ? ) in your tsconfig ?

**Comment by rutonyru** [comment]
My version of node is 20.11.1
My tsconfig.json is like this (if I understand your question, I don't have any definition for module or moduleResolution):
{
  "extends": "@adonisjs/tsconfig/tsconfig.app.json",
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "./build",
    "paths": {
      "#controllers/*": ["./app/controllers/*.js"],
      "#exceptions/*": ["./app/exceptions/*.js"],
      "#models/*": ["./app/models/*.js"],
      "#mails/*": ["./app/mails/*.js"],
      "#services/*": ["./app/services/*.js"],
      "#listeners/*": ["./app/listeners/*.js"],
      "#events/*": ["./app/events/*.js"],
      "#middleware/*": ["./app/middleware/*.js"],
      "#validators/*": ["./app/validators/*.js"],
      "#providers/*": ["./providers/*.js"],
      "#policies/*": ["./app/policies/*.js"],
      "#abilities/*": ["./app/abilities/*.js"],
      "#database/*": ["./database/*.js"],
      "#tests/*": ["./tests/*.js"],
      "#start/*": ["./start/*.js"],
      "#config/*": ["./config/*.js"],
    },
  },
}

**Comment by Julien-R44** [comment]
mmmh weird. try reloading your editor
i don't have any problems on my side, so it must be a configuration problem

**Comment by rutonyru** [comment]
Same error, even with a reboot. Don't worry about this issue. 
I'm building a AdonisJS api and I won't be stopped by this (I will use other ways to test it with Japa). 
If you have any idea that can help, or some check to do... I can do it of course ;)
Belle journée Julien et merci pour ton aide,
Antoine

**Comment by thetutlage** [comment]
Can you please share the `tests/bootstrap.ts` file, since you are using the package inside an AdonisJS app the plugin must be registered within the `tests/boostrap.ts` file.

**Comment by rutonyru** [comment]
Here it comes : tests/bootstrap.ts file
It is like it is registered ... 
```
import { assert } from '@japa/assert'
import { apiClient } from '@japa/api-client'
import app from '@adonisjs/core/services/app'
import type { Config } from '@japa/runner/types'
import { pluginAdonisJS } from '@japa/plugin-adonisjs'
import testUtils from '@adonisjs/core/services/test_utils'

/**
 * This file is imported by the "bin/test.ts" entrypoint file
 */

/**
 * Configure Japa plugins in the plugins array.
 * Learn more - https://japa.dev/docs/runner-config#plugins-optional
 */
export const plugins: Config['plugins'] = [assert(), apiClient(), pluginAdonisJS(app)]

/**
 * Configure lifecycle function to run before and after all the
 * tests.
 *
 * The setup functions are executed before all the tests
 * The teardown functions are executer after all the tests
 */
export const runnerHooks: Required<Pick<Config, 'setup' | 'teardown'>> = {
  setup: [],
  teardown: [],
}

/**
 * Configure suites by tapping into the test suite instance.
 * Learn more - https://japa.dev/docs/test-suites#lifecycle-hooks
 */
export const configureSuite: Config['configureSuite'] = (suite) => {
  if (['browser', 'functional', 'e2e'].includes(suite.name)) {
    return suite.setup(() => testUtils.httpServer().start())
  }
}

```

**Comment by Julien-R44** [comment]
it's not registered here. it should be in the `plugins` array

```ts
import { expectTypeOf } from '@japa/expect-type' // 👈

export const plugins: Config['plugins'] = [
	assert(), 
	apiClient(), 
	expectTypeOf(), // 👈👈👈 You are missing that
	pluginAdonisJS(app)
]
```

**Comment by rutonyru** [comment]
ok, nice ! Do I have missed something (probably :( )I'll check tomorrow morning :)

**Comment by Julien-R44** [comment]
Feel free to reopen if issue persists
